seoulrobotics/sensr_proto

- custom.proto
Add bg learning progress information to CustomMessage.
> Add bg learning progress.

- output.proto
- rest_api.proto
- type.proto
> added timestamp to history

- rest_api.proto
- type.proto
- Adopt a new History format.( position + timestamp)
> Merge for SDK

- custom.proto
- Add Replay and Record Info in CustomMessage so that user can check the status of Replay and Recording.
@young-seoulrobotics I temporary disabled `vehicle_oriented_fields_of_regard` because master branch of argos does not have any update on it. So, please enable this back when you merge your changes into master branch.
> Provide Replay and Recording Information through Output.

- custom.proto
- type.proto
- Add ProfilingResult message to provide processing time of a frame and memory usage.
> Add profiling data.

- type.proto
- Add characteristics field in ProfilingResult.
> Add Charateristic in ProfilingResult

- custom.proto
- Use `VehicleOrientedFieldsOfRegard` for field_of_regard.
> Merge Output field of regard

- custom.proto
https://seoulrobotics.atlassian.net/browse/AR-3637
> Fix FoR field number

- output.proto
fix number for `INITIALIZATION_ERROR`
> Init error status

- output.proto
- type.proto
https://seoulrobotics.atlassian.net/browse/AR-4037
> Replace Object.timestamp with time_offset

- type.proto
stemmed from https://github.com/seoulrobotics/argos/pull/2034
> add ZONE_TYPE_GATE to ZoneType

- type.proto
- add static zone type
- add retro_reflective flag
- resolve id conflict
> Sync proto update

- output.proto
- Add `VERSION_MISMATCH` algo node health status.
> Add version mismatch error statu in algo node.

- output.proto
- add has_objects and has_zones to infer whether the field what actually set or not
> add has_objects and has_zones fields to stream output message

- type.proto
https://seoulrobotics.atlassian.net/browse/BMW-556
> Replace object's time_offset with an absolute timestamp

- output.proto
- type.proto
JIRA Issue: https://seoulrobotics.atlassian.net/browse/BMW-606
> Remove static objects

- output.proto
Add online recalibration event message
> [AR-5945] add online recalibration event

- output.proto
Cherry-pick to master: https://github.com/seoulrobotics/sensr_proto/pull/46
> [AR-5945] cherry-pick: add online recalibration event

- global_type.proto
- output.proto
Change euler angles vector to a quaternion for the recalibration event
> [AR-5988] euler angles to quaternion recalibration event

- global_type.proto
- output.proto
Cherry-pick to master: https://github.com/seoulrobotics/sensr_proto/pull/49
> [AR-5988] cherry-pick: change the euler angles representation to quaternion

- output.proto
* add storage shortage node status for algo nodes
> [AR-6105] add storage shortage node status for algo nodes

- type.proto
* From https://github.com/seoulrobotics/sensr_proto/pull/54
* SENSR-S PR: https://github.com/seoulrobotics/argos/pull/4165
> [AR-6309] Background Removal Zone (#54)

- output.proto
* Add edge node status under SystemHealth::Node
> Add edge node status

- output.proto
* revert https://github.com/seoulrobotics/sensr_proto/commit/2c65524005cf79ac06e39e9320475b7baadf8d17 which does break backwards compatibility and is therefore not compliant
> [AR-6801] revert non compliant change

- macgyver.proto
Reverts seoulrobotics/sensr_proto#63
> Revert "feat: add custom event type"
